# Generated by Django 2.2.5 on 2019-11-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piopio_be.Post')),
                ('user_mentioned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mentioned', to=settings.AUTH_USER_MODEL)),
                ('user_mentioning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mentioning', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
