# Generated by Django 2.2.6 on 2019-12-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ManyToManyField(blank='true', related_name='_post_parent_+', to='piopio_be.Post'),
        ),
    ]
