# Generated by Django 2.2.5 on 2019-12-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
