# Generated by Django 2.2.6 on 2019-12-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0003_post_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ManyToManyField(related_name='_post_parent_+', to='piopio_be.Post'),
        ),
    ]
