# Generated by Django 2.2.6 on 2019-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0003_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='follower', to='piopio_be.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(related_name='following', to='piopio_be.Profile'),
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
