# Generated by Django 2.2.6 on 2019-12-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0004_auto_20191203_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reported',
            field=models.ManyToManyField(related_name='reported', to='piopio_be.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ManyToManyField(related_name='child', to='piopio_be.Post'),
        ),
    ]
