# Generated by Django 2.2.5 on 2019-12-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0005_auto_20191203_1420'),
        ('piopio_be', '0003_user_blocked_users'),
        ('piopio_be', '0003_trendingtopic'),
    ]

    operations = [
    ]
