# Generated by Django 2.2.6 on 2019-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0005_auto_20191030_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
