# Generated by Django 2.2.5 on 2019-12-05 18:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0006_merge_20191205_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
