# Generated by Django 2.2.6 on 2019-11-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0007_auto_20191102_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorited_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='retweeted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='favorited',
            field=models.ManyToManyField(related_name='favorited', to='piopio_be.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='retweeted',
            field=models.ManyToManyField(related_name='retweeted', to='piopio_be.Post'),
        ),
    ]
