# Generated by Django 2.2.5 on 2019-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piopio_be', '0008_auto_20191118_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
